// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetServers():Promise<Array<main.Server>>;

export function Greet(arg1:string):Promise<string>;

export function ModifyServer(arg1:main.Server):Promise<void>;

export function RemoveServer(arg1:string):Promise<void>;
