// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddCommand(arg1:main.Command):Promise<void>;

export function AddServer(arg1:main.Server):Promise<void>;

export function ExecCommand(arg1:string,arg2:string):Promise<void>;

export function GetCommands():Promise<Array<main.Command>>;

export function GetServers():Promise<Array<main.Server>>;

export function Greet(arg1:string):Promise<string>;

export function RemoveCommand(arg1:string):Promise<void>;

export function RemoveServer(arg1:string):Promise<void>;

export function SimpleExecCommand(arg1:string,arg2:string):Promise<main.SimpleExecCmdResult>;
