// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCommand(arg1) {
  return window['go']['main']['App']['AddCommand'](arg1);
}

export function AddServer(arg1) {
  return window['go']['main']['App']['AddServer'](arg1);
}

export function ExecCommand(arg1, arg2) {
  return window['go']['main']['App']['ExecCommand'](arg1, arg2);
}

export function GetCommands() {
  return window['go']['main']['App']['GetCommands']();
}

export function GetServers() {
  return window['go']['main']['App']['GetServers']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function RemoveCommand(arg1) {
  return window['go']['main']['App']['RemoveCommand'](arg1);
}

export function RemoveServer(arg1) {
  return window['go']['main']['App']['RemoveServer'](arg1);
}
