// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExecCommand(arg1) {
  return window['go']['main']['App']['ExecCommand'](arg1);
}

export function GetCommands() {
  return window['go']['main']['App']['GetCommands']();
}

export function GetServers() {
  return window['go']['main']['App']['GetServers']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ModifyCommand(arg1) {
  return window['go']['main']['App']['ModifyCommand'](arg1);
}

export function ModifyServer(arg1) {
  return window['go']['main']['App']['ModifyServer'](arg1);
}

export function RemoveCommand(arg1) {
  return window['go']['main']['App']['RemoveCommand'](arg1);
}

export function RemoveServer(arg1) {
  return window['go']['main']['App']['RemoveServer'](arg1);
}
